apiVersion: v1
kind: Namespace
metadata:
  name: infra-gateway

---

kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  namespace: infra-gateway
  name: external-http
spec:
  gatewayClassName: gke-l7-gxlb
  addresses:
  - type: NamedAddress
    value: shared-gateway-ipv4 # Created out of band.
  listeners:
  - name: medtracker-net-https
    protocol: HTTPS
    port: 443
    hostname: medtracker.dev
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
      namespaces:
        from: Selector
        selector:
          matchLabels:
            row-major.net/gateway-application: "medtracker-dev"
    tls:
      mode: Terminate
      options:
        networking.gke.io/pre-shared-certs: medtracker-dev # Created out of band.
  - name: www-row-major-net-https
    protocol: HTTPS
    port: 443
    hostname: www.row-major.net
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
      namespaces:
        from: Selector
        selector:
          matchLabels:
            row-major.net/gateway-application: "row-major-net"
    tls:
      mode: Terminate
      options:
        # Created out of band, covers both www.row-major.net and row-major.net
        networking.gke.io/pre-shared-certs: row-major-net
  - name: row-major-net-https
    protocol: HTTPS
    port: 443
    hostname: row-major.net
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
      namespaces:
        from: Selector
        selector:
          matchLabels:
            row-major.net/gateway-application: "row-major-net"
    tls:
      mode: Terminate
      options:
        # Created out of band, covers both www.row-major.net and row-major.net
        networking.gke.io/pre-shared-certs: row-major-net
    