kind: Namespace
apiVersion: v1
metadata:
  name: sharded-controller

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sharder
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]


---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configmap-watcher
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sharded-controller
  name: configmap-writer
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["put", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sharded-controller-is-a-sharder
  namespace: sharded-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sharder
subjects:
- kind: ServiceAccount
  namespace: sharded-controller
  name: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sharded-controller-is-a-configmap-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: configmap-watcher
subjects:
- kind: ServiceAccount
  namespace: sharded-controller
  name: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: sharded-controller
  name: sharded-controller-is-a-configmap-writer
roleRef:
  apiGroup: rbac.authoriztaion.k8s.io
  kind: Role
  name: configmap-writer
subjects:
- kind: ServiceAccount
  namespace: sharded-controller
  name: default

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharded-controller
  namespace: sharded-controller
  labels:
    app: sharded-controller
spec:
  selector:
    matchLabels:
      app: sharded-controller
  replicas: 3
  template:
    metadata:
      labels:
        app: sharded-controller
    spec:
      containers:
      - name: sharded-controller
        image: gcr.io/bomsync-214520/shardedcontroller:1604287923
        args:
          - --shard_namespace=$(POD_NAMESPACE)
          - --shard_selector=app=sharded-controller
          - --self_pod_name=$(POD_NAME)
          - --config_map_namespace=$(POD_NAMESPACE)
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
