# This file is overwritten by CI.
#
# Refer to //infra-tools/bump-manifest to see how it is generated.
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: medtracker
  name: webui
spec:
  template:
    spec:
      containers:
      - name: main
        image: gcr.io/bomsync-214520/medtracker/webui:0a01574fabe8617749b3c798b9c7ae54c5ef4522
