# This file is overwritten by CI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: row-major-web-content-deployment
  namespace: row-major-web
spec:
  template:
    spec:
      containers:
        - name: row-major-web-content
          image: gcr.io/bomsync-214520/webalator:81f235e220d6ecd7518a8012e7e5954e691b4eed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharded-controller
  namespace: sharded-controller
spec:
  template:
    spec:
      containers:
        - name: sharded-controller
          image: gcr.io/bomsync-214520/shardedcontroller:81f235e220d6ecd7518a8012e7e5954e691b4eed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rumor-mill
  namespace: rumor-mill
spec:
  template:
    spec:
      containers:
      - name: main
        image: gcr.io/bomsync-214520/rumor-mill:81f235e220d6ecd7518a8012e7e5954e691b4eed
