# This file is overwritten by CI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: row-major-web-content-deployment
  namespace: row-major-web
spec:
  template:
    spec:
      containers:
        - name: row-major-web-content
          image: gcr.io/bomsync-214520/webalator:7a7a7486b9958a98400ec369c5f272d76e424f66
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharded-controller
  namespace: sharded-controller
spec:
  template:
    spec:
      containers:
        - name: sharded-controller
          image: gcr.io/bomsync-214520/shardedcontroller:7a7a7486b9958a98400ec369c5f272d76e424f66
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rumor-mill
  namespace: rumor-mill
spec:
  template:
    spec:
      containers:
      - name: main
        image: gcr.io/bomsync-214520/rumor-mill:7a7a7486b9958a98400ec369c5f272d76e424f66
