# This file is overwritten by CI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: row-major-web-content-deployment
  namespace: row-major-web
spec:
  template:
    spec:
      containers:
        - name: row-major-web-content
          image: gcr.io/bomsync-214520/webalator:bc93c177bdcb7016967b61561745d6748fbd1da0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharded-controller
  namespace: sharded-controller
spec:
  template:
    spec:
      containers:
        - name: sharded-controller
          image: gcr.io/bomsync-214520/shardedcontroller:bc93c177bdcb7016967b61561745d6748fbd1da0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rumor-mill
  namespace: rumor-mill
spec:
  template:
    spec:
      containers:
      - name: main
        image: gcr.io/bomsync-214520/rumor-mill:bc93c177bdcb7016967b61561745d6748fbd1da0
