apiVersion: v1
kind: Namespace
metadata:
  name: row-major-web
---
apiVersion: v1
kind: Namespace
metadata:
  name: rumor-mill
---
apiVersion: v1
kind: Namespace
metadata:
  name: sharded-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: webalator@bomsync-214520.iam.gserviceaccount.com
  name: webalator
  namespace: row-major-web
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-writer
  namespace: sharded-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configmap-watcher
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sharder
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sharded-controller-is-a-configmap-writer
  namespace: sharded-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: configmap-writer
subjects:
- kind: ServiceAccount
  name: default
  namespace: sharded-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sharded-controller-is-a-sharder
  namespace: sharded-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sharder
subjects:
- kind: ServiceAccount
  name: default
  namespace: sharded-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sharded-controller-is-a-configmap-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: configmap-watcher
subjects:
- kind: ServiceAccount
  name: default
  namespace: sharded-controller
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: row-major-web
    component: content
  name: row-major-web-content-service
  namespace: row-major-web
spec:
  ports:
  - name: http
    port: 8001
    protocol: TCP
    targetPort: 8080
  selector:
    app: row-major-web
    component: content
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: row-major-web
    component: content
  name: row-major-web-content-deployment
  namespace: row-major-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: row-major-web
      component: content
  template:
    metadata:
      labels:
        app: row-major-web
        component: content
    spec:
      containers:
      - command:
        - /app/webalator/webalator
        - --static-content-dir=webalator/static-content
        - --template-dir=webalator/content
        - --listen=0.0.0.0:8080
        - --debug-listen=0.0.0.0:8081
        - --logtostderr=true
        - --enable-profiling
        - --enable-tracing
        - --tracing-ratio=1.0
        - --enable-metrics
        image: gcr.io/bomsync-214520/webalator:81f235e220d6ecd7518a8012e7e5954e691b4eed
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: row-major-web-content
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
      serviceAccountName: webalator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rumor-mill
  name: rumor-mill
  namespace: rumor-mill
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rumor-mill
  template:
    metadata:
      labels:
        app: rumor-mill
    spec:
      containers:
      - command:
        - /app/rumor-mill/rumor-mill
        - --debug-listen=0.0.0.0:8001
        - --logtostderr=true
        - --monitoring=true
        - --monitoring-trace-ratio=1.0
        - --data-dir=rumor-mill-state-prod-us-west1
        image: gcr.io/bomsync-214520/rumor-mill:81f235e220d6ecd7518a8012e7e5954e691b4eed
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 10
        name: main
        ports:
        - containerPort: 8001
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 10
      serviceAccountName: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sharded-controller
  name: sharded-controller
  namespace: sharded-controller
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sharded-controller
  template:
    metadata:
      labels:
        app: sharded-controller
    spec:
      containers:
      - args:
        - --shard_namespace=$(POD_NAMESPACE)
        - --shard_selector=app=sharded-controller
        - --self_pod_name=$(POD_NAME)
        - --config_map_namespace=$(POD_NAMESPACE)
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: gcr.io/bomsync-214520/shardedcontroller:81f235e220d6ecd7518a8012e7e5954e691b4eed
        name: sharded-controller
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.global-static-ip-name: row-major-web
    networking.gke.io/managed-certificates: www-row-major-net,row-major-net
    networking.gke.io/v1beta1.FrontendConfig: row-major-web
  labels:
    app: row-major-web
    component: ingress
  name: ingress6
  namespace: row-major-web
spec:
  backend:
    serviceName: row-major-web-content-service
    servicePort: http
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: row-major-web
  namespace: row-major-web
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: FOUND
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: row-major-net
  namespace: row-major-web
spec:
  domains:
  - row-major.net
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: www-row-major-net
  namespace: row-major-web
spec:
  domains:
  - www.row-major.net
