# This file is overwritten by CI.
#
# Refer to //infra-tools/bump-manifest to see how it is generated.
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: row-major-web
  name: row-major-web-content-deployment
spec:
  template:
    spec:
      containers:
      - name: row-major-web-content
        image: gcr.io/bomsync-214520/webalator:c9fbb03fe7d17e3aef4adffb6b1ac0d6004335cf
