# This file is overwritten by CI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rumor-mill
  namespace: rumor-mill
spec:
  template:
    spec:
      containers:
      - name: main
        image: gcr.io/bomsync-214520/rumor-mill:e9f598ff7a13970745099d27c5d1c3641491f7ee
