# This file is overwritten by CI.
#
# Refer to //infra-tools/bump-manifest to see how it is generated.
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rumor-mill
  name: rumor-mill
spec:
  template:
    spec:
      containers:
      - name: main
        image: gcr.io/bomsync-214520/rumor-mill:78073063fd306542ae97c76eec595c4cb5f25f0e
