# This file is overwritten by CI.
#
# Refer to //infra-tools/bump-manifest to see how it is generated.
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sharded-controller
  name: sharded-controller
spec:
  template:
    spec:
      containers:
      - name: sharded-controller
        image: gcr.io/bomsync-214520/shardedcontroller:3a74542b8df3d7153a1a43000cd36cac182c70bc
