steps:
- name: 'gcr.io/cloud-marketplace-containers/google/bazel'
  entrypoint: 'bazel'
  args: ['test', '--', '//...', '-//vendor/...']

# Load our built webalator image into the local Docker cache.
- name: 'gcr.io/cloud-marketplace-containers/google/bazel'
  entrypoint: 'bazel'
  args: ['run', '//webalator:webalator_image', '--', '--norun']

- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'bazel/webalator:webalator_image', 'gcr.io/$PROJECT_ID/webalator:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'bazel/webalator:webalator_image', 'gcr.io/$PROJECT_ID/webalator:${_COMMIT_SHA}']

images:
  - 'gcr.io/$PROJECT_ID/webalator:latest'
  - 'gcr.io/$PROJECT_ID/webalator:${_COMMIT_SHA}'

logsBucket: 'gs://cloud-build-logs.row-major.net'
