# Apply this namespace to all resources
namespace: row-major-web

resources:
- row-major-web.yaml
imageTags:
- digest: sha256:3f890e318d0e849526e3aace86adf42a68b50d9ca8c9b7fcca4cd1de2dc83d58
  name: gcr.io/bomsync-214520/row-major-website
apiVersion: v1beta1
kind: Kustomization
