# Apply this namespace to all resources
namespace: row-major-web

resources:
- row-major-web.yaml
imageTags:
- digest: sha256:7253f16a2bd8e65142dfe9a31377b4d7f81d931532cbfe512a0b7acd3723d413
  name: gcr.io/bomsync-214520/row-major-website
apiVersion: v1beta1
kind: Kustomization
