kind: Namespace
apiVersion: v1
metadata:
  name: row-major-web

---

kind: Service
apiVersion: v1
metadata:
  name: row-major-web-content-service
  namespace: row-major-web
  labels:
    app: row-major-web
    component: content
spec:
  type: NodePort
  selector:
    app: row-major-web
    component: content
  ports:
    - name: http
      protocol: TCP
      port: 8001
      targetPort: 80

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: row-major-web-content-deployment
  namespace: row-major-web
  labels:
    app: row-major-web
    component: content
spec:
  selector:
    matchLabels:
      app: row-major-web
      component: content
  replicas: 1
  template:
    metadata:
      labels:
        app: row-major-web
        component: content
    spec:
      containers:
        - name: row-major-web-content
          image: gcr.io/bomsync-214520/row-major-website:1582449908
          ports:
            - containerPort: 80

---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: www-row-major-net
spec:
  domains:
    - www.row-major.net
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: row-major-net
spec:
  domains:
    - row-major.net
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: ingress4
  namespace: row-major-web
  labels:
    app: row-major-web
    component: ingress
  annotations:
    networking.gke.io/managed-certificates: www-row-major-net,row-major-net
    kubernetes.io/ingress.global-static-ip-name: "row-major-web"
    # This doesn't work yet.  Watch
    # https://github.com/kubernetes/ingress-gce/issues/51 and
    # https://issuetracker.google.com/issues/35904733
    #
    #kubernetes.io/ingress.allow-http: "false"
    #ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  backend:
    serviceName: row-major-web-content-service
    servicePort: http
