apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

patchesStrategicMerge:
  - medtracker-poller-production-images.merge.yaml
  - medtracker-webui-production-images.merge.yaml
