name: build
on: [push]

env:
  BAZEL_VERSION: "5.1.0"

jobs:
  ping-gcp:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: 'Setup Google Cloud Authentication'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/508647401058/locations/global/workloadIdentityPools/ci-federation/providers/github-actions'
        service_account: 'github-actions@row-major-ci.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 390.0.0'

    # - name: 'Use gcloud CLI'
    #   run: 'gcloud container clusters list --project=bomsync-214520 --billing-project=bomsync-214520'
    
    - run: 'curl -L https://releases.bazel.build/${BAZEL_VERSION}/release/bazel-${BAZEL_VERSION}-linux-x86_64 > bazel'
    - run: 'chmod +x bazel'
    - run: './bazel test -- //... -//cloud-checkout/...'
    - run: 'IMAGE_REPO=bomsync-214520 IMAGE_TAG=${GITHUB_SHA} ./bazel run //medtracker/cmd/poller:poller_push'
    - run: 'IMAGE_REPO=bomsync-214520 IMAGE_TAG=${GITHUB_SHA} ./bazel run //medtracker/cmd/webui:webui_push'